### ISSUE TITLE
Refuses to deploy on system with PHP 7.3

### ISSUE THREAD

**Issue by stanelie** [Chevereto/Installer#10]
The installer refuses to install on my system, latest raspbian with PHP 7.3.

![Screen Shot 2020-03-26 at 10 25 43](https://user-images.githubusercontent.com/2935029/77657893-4d1a7a80-6f4c-11ea-9cef-244618e3183d.png)

However, the changelog says that it is compatible with PHP 7.3 since may 2019 : 

![Screen Shot 2020-03-26 at 10 27 45](https://user-images.githubusercontent.com/2935029/77658046-8357fa00-6f4c-11ea-8ac0-af6632e1d1e0.png)

**Comment by rodber** [comment]
Chevereto != Chevereto-Free

Chevereto-Free still doesn't support PHP 7.3. It should support 7.4 in the next revision.
