### ISSUE TITLE
Also facing the problem:Error performing HTTP request

### ISSUE THREAD

**Issue by BobAnkh** [Chevereto/Installer#11]
I don't know what causes my problem, could you help me fix it?

**system info:**
Ubuntu 18.04LTS
Apache/2.4.29 (Ubuntu)
Mysql 5.7.29
PHP v7.2.24

What I did:
```
git clone https://github.com/Chevereto/installer.git
mv installer image
chmod 777 image -Rf
chown www-data:www-data image -Rf
```
And then I visit the website

Error:
![image](https://user-images.githubusercontent.com/44333669/80369462-e7aa0880-88c0-11ea-8cb8-28b74a9e1059.png)

Log of console:
![image](https://user-images.githubusercontent.com/44333669/80369498-f395ca80-88c0-11ea-8af6-e6d4bfbeeb4d.png)

Is there something else I need to configure before visit the website?

If there is more info I should provide please contact me.

Thank you very much for helping me!

**Comment by rodber** [comment]
I've added a documentation that outlines how to handle installer issues: https://chevereto.com/docs/installer

When I developed the installer I did't realize it will get this picky with server setups. It is a cool idea, but it depends on many stuff that can go wrong 😔.
