### ISSUE TITLE
"Error performing HTTP request"

### ISSUE THREAD

**Issue by EricLauber** [Chevereto/Installer#13]
Hello. I am not a strong in Linux admin so apologies in advance if I haven't provided enough information. I am attempting to install Chevereto on an Ubuntu Server 20.04 LTS. 
- Apache: 10.0.11.10 
- PHP: 7.4.3
- MariaDB 10.4

I confirmed that Apache and PHP were working and created a database. I am able to bring up the Installer page for the free edition and to run it.  The installer fails, but reports the following.
```
Server 10.0.11.10 PHP 7.4.3
Software has been set to: chevereto-free
Database cheveretodb OK
Detecting existing cPanel .htaccess handlers
No .htaccess found
Downloading latest chevereto-free release
Downloaded chevereto-pkg-a4f202c7.zip (4.7 MB @3.63MB/s.)
Extracting chevereto-pkg-a4f202c7.zip
Extraction completeted (424 files in 0.23s)
Creating app/settings.php file
Settings file OK
Performing system setup
Error performing HTTP request
Process aborted
```
Is there some port or permission I may have missed that I need to enable on the server in order for the installer to continue?

**Comment by rodber** [comment]
Read the docs: https://chevereto.com/docs/installer
