### ISSUE TITLE
[Feature Request] Docker implementation for paid users.

### ISSUE THREAD

**Issue by gkoerk** [Chevereto/Installer#3]
I am a happy paid user of Chevereto, but I haven't actually been able to deploy it. That's because I run my self-hosted applications on a (fairly powerful) NAS, and so my OS is limited. However, my NAS unit (like almost every one sold by the major vendors) supports Docker. I am able to self-host my other applications all side-by-side via Docker, behind a reverse proxy.  So personally, I would be thrilled with a maintained deployment of Chevereto in Docker Hub. (Note that I have had Chevereto running successfully in Docker, but it never felt stable enough for production use, and I had to manage the Dockerfile myself: there was not automated/updated build.

I humbly offer two arguments commending this feature. First, this could potentially open the market for Chevereto Paid as well, so long as you require a paid license to deploy via docker (lots of options here).  Many NAS owners use them to store the entire photo collection, and none of the NAS vendors' Photo Management solutions have proved satisfying to the user communities. Furthermore, the homelab/self-hosting community is heavily invested in docker for a variety of reasons. While my primary motivation might be selfish, consider the possibility that making available a docker image could broaden your customer base significantly.

My last argument is not nearly as strong: many successful open-source software projects are either moving to Docker releases for portability and ease of installation / support, or adding Docker support to their existing deployment mechanisms. This argument boils down to, "everyone else is doing it, so should we." 😃

**Comment by rodber** [comment]
Check this: https://hub.docker.com/r/nmtan/chevereto/
