### ISSUE TITLE
free edition install faild

### ISSUE THREAD

**Issue by houguang** [Chevereto/Installer#5]
![image](https://user-images.githubusercontent.com/1720347/60406001-3544de80-9be6-11e9-835c-e20448ff3833.png)
![image](https://user-images.githubusercontent.com/1720347/60406011-4130a080-9be6-11e9-9899-229ab176dfb8.png)
download file faild

![image](https://user-images.githubusercontent.com/1720347/60406212-5ce87680-9be7-11e9-9ecd-b0901b8ba835.png)
console panel message

**Comment by rodber** [comment]
Provide the actual server error log, is the installer.error.log file.

Also, provide your system versions (php, mysql, etc.)
