### ISSUE TITLE
Error performing HTTP request

### ISSUE THREAD

**Issue by SlowFlight** [Chevereto/Installer#6]
![Error](https://user-images.githubusercontent.com/40648494/62355373-73b11e80-b541-11e9-860f-6b85e5053ef8.PNG)
Centos7
PHP: 7.2.19
Mysql: 8.0.17
Apache: 2.4.6
![php](https://user-images.githubusercontent.com/40648494/62355438-9cd1af00-b541-11e9-8ddd-eb847b16c86e.PNG)
![Mysql](https://user-images.githubusercontent.com/40648494/62355446-9fcc9f80-b541-11e9-95d6-2f623d325836.PNG)
![Apache](https://user-images.githubusercontent.com/40648494/62355451-a22ef980-b541-11e9-9493-b5954771abbd.PNG)

**Comment by rodber** [comment]
You are getting a client issue, post the client side (xhr on your browser console).

**Comment by SlowFlight** [comment]
> You are getting a client issue, post the client side (xhr on your browser console).

Thanks, and here is the picture, but not sure if it is what you asked
![XHR](https://user-images.githubusercontent.com/40648494/62404768-d3530c80-b5c9-11e9-811e-144e2ee3eadf.PNG)

**Comment by SlowFlight** [comment]
![404](https://user-images.githubusercontent.com/40648494/62404890-ace1a100-b5ca-11e9-9ff2-11149e2c1902.PNG)

**Comment by rodber** [comment]
What I'm looking for is the error that triggers the HTTP issue. From the log, is is a 404 meaning that the file doesn't exists (installer file).

The installer self removes the file but in the very last step. Why is being deleted in that early stage is something that needs your investigation.

What is the contents of installer.error.log?

**Comment by misumisery** [comment]
same problem here
![image](https://user-images.githubusercontent.com/16536747/62910540-761e3e80-bdb3-11e9-8d7e-94164dd4dec4.png)
