### ISSUE TITLE
Error: Unable to parse server response. The installer is expecting a JSON response, but your server thrown this:

### ISSUE THREAD

**Issue by wildwind0** [Chevereto/Installer#7]
Unable to round-trip http request to upstream: read tcp 219.223.174.227:46458->47.52.165.129:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by ghost** [comment]
Got the same error but <b>Chevereto Free error:</b> Internal Server Error

**Comment by szluyu99** [comment]
so can someone tell me how to solve?@@

**Comment by ghost** [comment]
No one knows yet, sorry @szluyu99

**Comment by rodber** [comment]
Hi, sorry for the late response.

> Unable to round-trip http request to upstream: read tcp 219.223.174.227:46458->47.52.165.129:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

The address `47.52.165.129` is on ALICLOUD-HK, I assume that is the server where you are running the installer. If you get a timeout then chances are that the process is taking too long (or the server is prematurely timing out).

Let me address that the Installer performs several tasks, being `download` and `extraction` potential pitfalls for timeouts. The installer [will try](https://github.com/Chevereto/installer/blob/master/installer.php#L672) to use all the time possible when the server allows to override that setting, but even in that case it could fail.

I believe that the best advice that I can give you is to go for the manual installation process as described here: https://chevereto.com/docs/install (there are also other alternatives like Softaculous or Docker).

**Comment by rodber** [comment]
> Got the same error but Chevereto Free error: Internal Server Error

That's a different error, affecting a *different* software (the Installer is not the same software as Chevereto-Free). For your case, enable debug mode 3 as described here: https://chevereto.com/docs/debug and open a ticket here: https://chevereto.com/support

In case you didn't knew, Chevereto Support is also available for Chevereto-Free.
